services:
  bot:
    build: .
    command: ["-t", "$TOKEN"]
    init: true
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - type: volume
        source: bhc
        target: /var/lib/bhc/data
volume:
  - bhc: